[color]
    primary = "#2e3440" # polar night
    secondary = "#eceff4" # snow storm
    tertiary = "#bf616a" # aurora red

[env]
    applyMode = "all" # possible values are "all", "terminal", "appearance", or "vscode"
